version: "2"
services:
   configserver:
      image: hyness/spring-cloud-config-server
      network_mode: host
      volumes:
         - "..:/config"
      environment:
         SPRING_CLOUD_CONFIG_SERVER_GIT_URI: file:///config
