version: "2"
services:
   namenode:
      image: elek/hadoop-hdfs-namenode:${HADOOP_VERSION}
      network_mode: host
      volumes:
         - "/tmp:/data"
      environment:
         CORE-SITE_fs.default.name: "hdfs://localhost:9000"
         HDFS-SITE_dfs.namenode.rpc-address: "localhost:9000"
         HDFS-SITE_dfs.namenode.name.dir: /data/namenode
         HDFS-SITE_dfs.namenode.http-bind-host: 0.0.0.0
   datanode:
      image: elek/hadoop-hdfs-datanode:${HADOOP_VERSION}
      volumes:
         - "/tmp:/data"
      network_mode: host
      environment:
         CORE-SITE_fs.default.name: "hdfs://localhost:9000"
         HDFS-SITE_dfs.namenode.rpc-address: "localhost:9000"
         HDFS-SITE_dfs_datanode_data_dir: /data/datanode
         HDFS-SITE_dfs.namenode.http-bind-host: 0.0.0.0
   resourcemanager:
      image: elek/hadoop-yarn-resourcemanager:${HADOOP_VERSION}
      network_mode: host
      environment:
         CORE-SITE_fs.default.name: "hdfs://localhost:9000"
         HDFS-SITE_dfs.namenode.rpc-address: "localhost:9000"
         HDFS-SITE_dfs.datanode.data.dir: /data/datanode
         YARN-SITE_yarn.resourcemanager.hostname: "localhost"
         YARN-SITE_yarn.nodemanager.vmem-check-enabled: "false"
         YARN-SITE_yarn.nodemanager.pmem-check-enabled: "false"
         YARN-SITE_yarn.nodemanager.delete.debug-delay-sec: 600
         YARN-SITE_yarn.resourcemanager.bind-host: "0.0.0.0"
   nodemanager:
      image: elek/hadoop-yarn-nodemanager:${HADOOP_VERSION}
      network_mode: host
      environment:
         CORE-SITE_fs.default.name: "hdfs://localhost:9000"
         HDFS-SITE_dfs.namenode.rpc-address: "localhost:9000"
         HDFS-SITE_dfs.datanode.data_dir: /data/datanode
         YARN-SITE_yarn.resourcemanager.hostname: "localhost"
         YARN-SITE_yarn.nodemanager.vmem-check-enabled: "false"
         YARN-SITE_yarn.nodemanager.pmem-check-enabled: "false"
         YARN-SITE_yarn.nodemanager.delete.debug-delay-sec: 600
   zeppelin:
      image: elek/zeppelin
      network_mode: host
   zookeeper:
      image: elek/zookeeper
      network_mode: host
   hbasemaster:
      image: elek/hbase-master
      network_mode: host
      volumes:
         - "./regionservers:/opt/hbase/conf/regionservers"
      environment:
         HBASE_SITE_hbase.zookeeper.quorum: "localhost"
         HBASE_SITE_hbase.rootdir: "hdfs://localhost:9000/hbase"
   hbaseregion:
      image: elek/hbase-regionserver
      network_mode: host
      environment:
         HBASE_SITE_hbase.zookeeper.quorum: "localhost"
         HBASE_SITE_hbase.rootdir: "hdfs://localhost:9000/hbase"
