version: "2"
services:
   namenode:
      image: elek/hadoop-hdfs-namenode
      network_mode: host
      volumes:
         - "/tmp:/data"
      environment:
         CORE_SITE_fs_default_name: "hdfs://localhost:9000"
         HDFS_SITE_dfs_namenode_rpc-address: "localhost:9000"
         HDFS_SITE_dfs_namenode_name_dir: /data/namenode
         HDFS_SITE_dfs.namenode.http-bind-host: 0.0.0.0
   datanode:
      image: elek/hadoop-hdfs-datanode
      volumes:
         - "/tmp:/data"
      network_mode: host
      environment:
         CORE_SITE_fs_default_name: "hdfs://localhost:9000"
         HDFS_SITE_dfs_namenode_rpc-address: "localhost:9000"
         HDFS_SITE_dfs_namenode_name_dir: /data/namenode
         HDFS_SITE_dfs_datanode_data_dir: /data/datanode
         HDFS_SITE_dfs.namenode.http-bind-host: 0.0.0.0
   resourcemanager:
      image: elek/hadoop-yarn-resourcemanager
      network_mode: host
      environment:
             CORE_SITE_fs_default_name: "hdfs://localhost:9000"
             HDFS_SITE_dfs_namenode_rpc-address: "localhost:9000"
             HDFS_SITE_dfs_datanode_data_dir: /data/datanode
             YARN_SITE_yarn.resourcemanager.hostname: "localhost"
             YARN_SITE_yarn.nodemanager.vmem-check-enabled: "false"
             YARN_SITE_yarn.nodemanager.pmem-check-enabled: "false"
             YARN_SITE_yarn.nodemanager.delete.debug-delay-sec: 600
             YARN_SITE_yarn.resourcemanager.bind-host: "0.0.0.0"
   nodemanager:
      image: elek/hadoop-yarn-nodemanager
      network_mode: host
      environment:
             CORE_SITE_fs_default_name: "hdfs://localhost:9000"
             HDFS_SITE_dfs_namenode_rpc-address: "localhost:9000"
             HDFS_SITE_dfs_datanode_data_dir: /data/datanode
             YARN_SITE_yarn.resourcemanager.hostname: "localhost"
             YARN_SITE_yarn.nodemanager.vmem-check-enabled: "false"
             YARN_SITE_yarn.nodemanager.pmem-check-enabled: "false"
             YARN_SITE_yarn.nodemanager.delete.debug-delay-sec: 600
   zeppelin:
      image: elek/zeppelin
      network_mode: host
   zookeeper:
      image: elek/zookeeper
      network_mode: host
   hbasemaster:
      image: elek/hbase-master
      network_mode: host
      volumes:
         - "./regionservers:/opt/hbase/conf/regionservers"
      environment:
         HBASE_SITE_hbase_zookeeper_quorum: "localhost"
         HBASE_SITE_hbase.rootdir: "hdfs://localhost:9000/hbase"
   hbaseregion:
      image: elek/hbase-regionserver
      network_mode: host
      environment:
         HBASE_SITE_hbase_zookeeper_quorum: "localhost"
         HBASE_SITE_hbase.rootdir: "hdfs://localhost:9000/hbase"
