version: "2"
services:
   namenode:
      image: elek/hadoop-hdfs-namenode
      network_mode: host
      volumes:
         - "/tmp:/data"
      environment:
         CORE_SITE_fs_default_name: "hdfs://localhost:9000"
         HDFS_SITE_dfs_namenode_rpc-address: "localhost:9000"
         HDFS_SITE_dfs_namenode_name_dir: /data/namenode
   datanode:
      image: elek/hadoop-hdfs-datanode
      volumes:
         - "/tmp:/data"
      network_mode: host
      environment:
         CORE_SITE_fs_default_name: "hdfs://localhost:9000"
         HDFS_SITE_dfs_namenode_rpc-address: "localhost:9000"
         HDFS_SITE_dfs_namenode_name_dir: /data/namenode
   resourcemanager:
      image: elek/hadoop-yarn-resourcemanager
      network_mode: host
      environment:
             CORE_SITE_fs_default_name: "hdfs://localhost:9000"
             HDFS_SITE_dfs_namenode_rpc-address: "localhost:9000"
             HDFS_SITE_dfs_datanode_data_dir: /data/datanode
             YARN_SITE_yarn.resourcemanager.hostname: "localhost"
             YARN_SITE_yarn.nodemanager.vmem-check-enabled: "false"
             YARN_SITE_yarn.nodemanager.pmem-check-enabled: "false"
             YARN_SITE_yarn.nodemanager.delete.debug-delay-sec: 600
   nodemanager:
      image: elek/hadoop-yarn-nodemanager
      network_mode: host
      environment:
             CORE_SITE_fs_default_name: "hdfs://localhost:9000"
             HDFS_SITE_dfs_namenode_rpc-address: "localhost:9000"
             HDFS_SITE_dfs_datanode_data_dir: /data/datanode
             YARN_SITE_yarn.resourcemanager.hostname: "localhost"
             YARN_SITE_yarn.nodemanager.vmem-check-enabled: "false"
             YARN_SITE_yarn.nodemanager.pmem-check-enabled: "false"
             YARN_SITE_yarn.nodemanager.delete.debug-delay-sec: 600

