version: "2"
services:
   namenode:
      image: elek/hadoop-hdfs-namenode:${HADOOP_VERSION}
      network_mode: host
      volumes:
         - "/tmp:/data"
      environment:
         CORE-SITE.XML_fs.default.name: "hdfs://localhost:9000"
         HDFS-SITE.XML_dfs.namenode.rpc-address: "localhost:9000"
         HDFS-SITE.XML_dfs.namenode.name.dir: /data/namenode
         HDFS-SITE.XML_dfs.namenode.http-bind-host: 0.0.0.0
         HDFS-SITE.XML_hadoop.proxyuser.root.hosts: "*"
         HDFS-SITE.XML_hadoop.proxyuser.root.groups: "*"
   datanode:
      image: elek/hadoop-hdfs-datanode:${HADOOP_VERSION}
      volumes:
         - "/tmp:/data"
      network_mode: host
      environment:
         CORE-SITE.XML_fs.default.name: "hdfs://localhost:9000"
         HDFS-SITE.XML_dfs.namenode.rpc-address: "localhost:9000"
         HDFS-SITE.XML_dfs_datanode_data_dir: /data/datanode
         HDFS-SITE.XML_dfs.namenode.http-bind-host: 0.0.0.0
   hivemetastore:
      image: elek/hive-metastore
      volumes:
         - "/tmp:/data"
      network_mode: host
      environment:
         CORE-SITE.XML_fs.default.name: "hdfs://localhost:9000"
         HDFS-SITE.XML_dfs.namenode.rpc-address: "localhost:9000"
         HDFS-SITE.XML_dfs_datanode_data_dir: /data/datanode
         HDFS-SITE.XML_dfs.namenode.http-bind-host: 0.0.0.0
         HIVE-SITE.XML_javax.jdo.option.ConnectionURL: "jdbc:derby:;databaseName=/data/hivemetastore;create=true"
         HIVE-SITE.XML_hive.metastore.warehouse.dir: /hive
   hiveserver2:
      image: elek/hive-hiveserver2
      volumes:
         - "/tmp:/data"
      network_mode: host
      environment:
         HADOOP_CONF_DIR: /opt/hive/conf
         CORE-SITE.XML_fs.default.name: "hdfs://localhost:9000"
         CORE-SITE.XML_fs.defaultFs: "hdfs://localhost:9000"
         HDFS-SITE.XML_dfs.namenode.rpc-address: "localhost:9000"
         HDFS-SITE.XML_dfs_datanode_data_dir: /data/datanode
         HDFS-SITE.XML_dfs.namenode.http-bind-host: 0.0.0.0
         HIVE-SITE.XML_hive.metastore.uris: thrift://localhost:9083
         HIVE-SITE.XML_hive.metastore.warehouse.dir: /hive
      command: /opt/hive/bin/hiveserver2
   resourcemanager:
      image: elek/hadoop-yarn-resourcemanager:${HADOOP_VERSION}
      network_mode: host
      environment:
         CORE-SITE.XML_fs.default.name: "hdfs://localhost:9000"
         HDFS-SITE.XML_dfs.namenode.rpc-address: "localhost:9000"
         HDFS-SITE.XML_dfs.datanode.data.dir: /data/datanode
         YARN-SITE.XML_yarn.resourcemanager.hostname: "localhost"
         YARN-SITE.XML_yarn.nodemanager.vmem-check-enabled: "false"
         YARN-SITE.XML_yarn.nodemanager.pmem-check-enabled: "false"
         YARN-SITE.XML_yarn.nodemanager.delete.debug-delay-sec: 600
         YARN-SITE.XML_yarn.resourcemanager.bind-host: "0.0.0.0"
   nodemanager:
      image: elek/hadoop-yarn-nodemanager:${HADOOP_VERSION}
      network_mode: host
      environment:
         CORE-SITE.XML_fs.default.name: "hdfs://localhost:9000"
         HDFS-SITE.XML_dfs.namenode.rpc-address: "localhost:9000"
         HDFS-SITE.XML_dfs.datanode.data_dir: /data/datanode
         YARN-SITE.XML_yarn.resourcemanager.hostname: "localhost"
         YARN-SITE.XML_yarn.nodemanager.vmem-check-enabled: "false"
         YARN-SITE.XML_yarn.nodemanager.pmem-check-enabled: "false"
         YARN-SITE.XML_yarn.nodemanager.delete.debug-delay-sec: 600
   zeppelin:
      image: elek/zeppelin
      network_mode: host
   zookeeper:
      image: elek/zookeeper
      network_mode: host
   hbasemaster:
      image: elek/hbase-master
      network_mode: host
      volumes:
         - "./regionservers:/opt/hbase/conf/regionservers"
      environment:
         HBASE-SITE.XML_hbase.zookeeper.quorum: "localhost"
         HBASE-SITE.XML_hbase.rootdir: "hdfs://localhost:9000/hbase"
   hbaseregion:
      image: elek/hbase-regionserver
      network_mode: host
      environment:
         HBASE-SITE.XML_hbase.zookeeper.quorum: "localhost"
         HBASE-SITE.XML_hbase.rootdir: "hdfs://localhost:9000/hbase"
