version: "2"
services:
   namenode:
      image: elek/hadoop-hdfs-namenode
      network_mode: host
      volumes:
         - "/tmp:/data"
      environment:
         CONFIG_TYPE: "consul-simple"
   datanode:
      image: elek/hadoop-hdfs-datanode
      volumes:
         - "/tmp:/data"
      network_mode: host
      environment:
         CONFIG_TYPE: "consul-simple"
   resourcemanager:
      image: elek/hadoop-yarn-resourcemanager
      network_mode: host
      environment:
         CONFIG_TYPE: "consul-simple"
   nodemanager:
      image: elek/hadoop-yarn-nodemanager
      network_mode: host
      environment:
         CONFIG_TYPE: "consul-simple"
   zeppelin:
      image: elek/zeppelin
      network_mode: host
      environment:
         CONFIG_TYPE: "consul-simple"
   zookeeper:
      image: elek/zookeeper
      network_mode: host
      environment:
         CONFIG_TYPE: "consul-simple"
   hbasemaster:
      image: elek/hbase-master
      network_mode: host
      environment:
         CONFIG_TYPE: "consul-simple"
   hbaseregion:
      image: elek/hbase-regionserver
      network_mode: host
      environment:
         CONFIG_TYPE: "consul-simple"
