---
- hosts: node1
  tasks:
     - name: namenode container
       docker_container:
          name: namenode
          image: elek/hadoop-hdfs-namenode
          state: started
          network_mode: host
          volumes: "/grid/0/:/data"
          pull: true
          env:
             CORE_SITE_fs_default_name: "hdfs://{{hostvars['node1'].ansible_hostname}}:9000"
             HDFS_SITE_dfs_namenode_rpc-address: "{{hostvars['node1'].ansible_hostname}}:9000"
             HDFS_SITE_dfs_namenode_name_dir: /data/namenode
- hosts: all
  tasks:
     - name: datanode container
       docker_container:
          name: datanode
          image: elek/hadoop-hdfs-datanode
          state: started
          network_mode: host
          volumes: "/grid/0/:/data"
          pull: true
          env:
             CORE_SITE_fs_default_name: "hdfs://{{hostvars['node1'].ansible_hostname}}:9000"
             HDFS_SITE_dfs_namenode_rpc-address: "{{hostvars['node1'].ansible_hostname}}:9000"
             HDFS_SITE_dfs_datanode_data_dir: /data/datanode
