---
- hosts: all
  tasks:
   - docker_container:
          name: logspout
          image: gliderlabs/logspout
          state: started
          network_mode: host
          restart_policy: always          
          volumes:
             - "/var/run/docker.sock:/var/run/docker.sock"
          env:
            PORT: 2323
