---
- hosts: node1
  tasks:
     - name: spark history server
       docker_container:
          name: sparkhistory
          image: elek/spark-history
          state: started
          network_mode: host
          volumes: "/grid/0/:/data"
          pull: true 
          env:
             CORE_SITE_fs_default_name: "hdfs://{{gateway}}:9000"
             HDFS_SITE_dfs_namenode_rpc-address: "{{gateway}}:9000"
             HDFS_SITE_dfs_namenode_name_dir: /data/namenode
             YARN_SITE_yarn.resourcemanager.hostname: "{{gateway}}"
