version: "2"
services:
   resourcemanager:
      image: elek/hadoop-yarn-resourcemanager
      network_mode: host
      environment:
             CORE_SITE_fs_default_name: "hdfs://localhost:9000"
             HDFS_SITE_dfs_namenode_rpc-address: "localhost:9000"
             HDFS_SITE_dfs_datanode_data_dir: /data/datanode
             YARN_SITE_yarn.resourcemanager.hostname: "localhost"
             YARN_SITE_yarn.nodemanager.vmem-check-enabled: "false"
             YARN_SITE_yarn.nodemanager.pmem-check-enabled: "false"
             YARN_SITE_yarn.nodemanager.delete.debug-delay-sec: 600
             YARN_SITE_yarn.resourcemanager.bind-host: "0.0.0.0"
   nodemanager:
      image: elek/hadoop-yarn-nodemanager
      network_mode: host
      environment:
             CORE_SITE_fs_default_name: "hdfs://localhost:9000"
             HDFS_SITE_dfs_namenode_rpc-address: "localhost:9000"
             HDFS_SITE_dfs_datanode_data_dir: /data/datanode
             YARN_SITE_yarn.resourcemanager.hostname: "localhost"
             YARN_SITE_yarn.nodemanager.vmem-check-enabled: "false"
             YARN_SITE_yarn.nodemanager.pmem-check-enabled: "false"
             YARN_SITE_yarn.nodemanager.delete.debug-delay-sec: 600
