---
- hosts: node1
  tasks:
     - name: resourcemanager container
       docker_container:
          name: zeppelin
          image: elek/zeppelin
          state: started
          network_mode: host
          volumes: "/grid/0/:/data"
          pull: true
          env:
             CORE_SITE_fs_default_name: "hdfs://{{hostvars['node1'].ansible_hostname}}:9000"
             CORE_SITE_fs.defaultFs: "hdfs://{{hostvars['node1'].ansible_hostname}}:9000"
             HDFS_SITE_dfs_namenode_rpc-address: "{{hostvars['node1'].ansible_hostname}}:9000"
             YARN_SITE_yarn.resourcemanager.hostname: "{{hostvars['node1'].ansible_hostname}}"
             YARN_SITE_yarn.nodemanager.vmem-check-enabled: false
             YARN_SITE_yarn.nodemanager.pmem-check-enabled: false
             YARN_SITE_yarn.nodemanager.delete.debug-delay-sec: 600
