version: "2"
services:
   namenode:
      container_name: namenode
      image: elek/hadoop-hdfs-namenode:3.0.0-alpha2
      network_mode: host
      volumes:
         - "{{env.DATA_DIR}}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "hdfs"
         HADOOP_CONF_DIR: "/opt/hadoop/etc/hadoop"
   datanode:
      container_name: datanode
      image: elek/hadoop-hdfs-datanode:3.0.0-alpha2
      volumes:
         - "{{env.DATA_DIR}}:/data"
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "hdfs"
   resourcemanager:
      container_name: resourcemanager
      image: elek/hadoop-yarn-resourcemanager:3.0.0-alpha2
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "yarn"
   nodemanager:
      container_name: nodemanager
      image: elek/hadoop-yarn-nodemanager:3.0.0-alpha2
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "yarn"
   zeppelin:
      container_name: zeppelin
      image: elek/zeppelin
      network_mode: host
      volumes:
         - "{{env.DATA_DIR}}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "zeppelin"
   zookeeper:
      container_name: zookeeper
      image: elek/zookeeper
      network_mode: host
      volumes:
         - "{{env.DATA_DIR}}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "zookeeper"
   hbasemaster:
      container_name: hbasemaster
      image: elek/hbase-master
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "hbase"
   hbaseregion:
      container_name: hbaseregion
      image: elek/hbase-regionserver
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "hbase"
   sparkhistory:
      container_name: sparkhistory
      image: elek/spark-history:2.1.0
      network_mode: host
      volumes:
         - "{{env.DATA_DIR}}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "spark"
   sparkmaster:
      container_name: sparkmaster
      image: elek/spark-master:2.0.2
      network_mode: host
      volumes:
         - "{{env.DATA_DIR}}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "spark"
   sparkslave:
      container_name: sparkslave
      image: elek/spark-slave:2.0.2
      network_mode: host
      volumes:
         - "{{env.DATA_DIR}}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "spark"
         SPARK_MASTER_HOST: "{{env.GATEWAY_HOST}}:7077"
   flume:
      container_name: flume
      image: elek/flume
      network_mode: host
      volumes:
         - "{{env.DATA_DIR}}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "flume"
